### ISSUE TITLE
Kanban Boards 

### ISSUE THREAD

**Issue by ba13malick** [akakpodorothee/portofolio#1]
N'oublies pas de mettre les taches de ton projet dans un Kanban board sur ce depot GitHub

**Comment by akakpodorothee** [comment]
ok merci coach. Mais s'il vous plaît coach c'est quoi kanban board?

**Comment by akakpodorothee** [comment]
les taches de mon projet  sont maintenant sur kanban board

**Comment by ba13malick** [comment]
Good job. Faudrait aussi ajouter les taches que tu as deja terminé et ceux que tu n'as pas encore commencé comme l'hébergement.

**Comment by akakpodorothee** [comment]
ok. merci coach
