### ISSUE TITLE
Code html

### ISSUE THREAD

**Issue by sethisbrothers** [akakpodorothee/portofolio#3]
Félicitation pour le travail éffectué.

Appliquer les propriétés css dans le fichier css vu que tu as déjà lié ton fichier html et non dans le code html.

Mettre les "Alt" au balisse img et les remplir.

Au lieu d'utiliser des div mettre les class à l'intérieur tu peux utilser les balises et mettre des class à l'intérieur directement par exemple (au lieu de div class="text" h3........../h3 tu peux faire h3 class="text".......h3 pour gagner en temps.

Revoir l'indentation de ton code html.

pour les class donne des noms qui ont des signification direct à ce que tu veux faire par exemple dans footer class=abc  au lieu de ça tu peux mettre class=contact.

le code est clair.

**Comment by akakpodorothee** [comment]
ok.Merci. mais si ça te dérange pas tu peux te déplacer m'expliquer
mieux,parce que je comprend bien ce dont tu me parle. Merci

Le mar. 3 mai 2022 à 12:54, Seth Kokou SODJI ***@***.***> a
écrit :

**Comment by akakpodorothee** [comment]
ok
