### ISSUE TITLE
Site 

### ISSUE THREAD

**Issue by sethisbrothers** [akakpodorothee/portofolio#5]
Site bien responsive parfait comme demandé.

Mais au niveau du projet les images sortent du cadre tu pourras réduire la taille des images pour qu'ils puissent tenir sur la page.

Mettre de gap dans les images du projet et mettre un titre à chaque projet.

Dans l'entête title tu peux mettre ton nom ou portfolio et non le laisser par défaut Document.

A propos et Compétences mettre cela visible et non caché serait bien pour les gens qui ne peuvent pas utiliser la souris pour naviguer sur la page.

**Comment by akakpodorothee** [comment]
ok.merci

**Comment by akakpodorothee** [comment]
ok

Le mar. 3 mai 2022 à 13:22, Seth Kokou SODJI ***@***.***> a
écrit :
